# Generated by Django 3.1.4 on 2020-12-11 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('event', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
